version: '3.3'
services:
  db:
    image: mysql:8.0 # 8.0 since mysql workbench doesn't support newer versions well
    container_name: mysql
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted
    command: --performance-schema --secure-file-priv=""
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: