CREATE SCHEMA IF NOT EXISTS repetition_m106 DEFAULT CHARACTER SET = utf8mb4;
USE repetition_m106;

CREATE TABLE IF NOT EXISTS tbl_fahrer (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(45) NOT NULL,
    Vorname VARCHAR(45) NOT NULL,
    Telefonnummer VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS tbl_disponent (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(45) NOT NULL,
    Vorname VARCHAR(45) NOT NULL,
    Telefonnummer VARCHAR(45)
);